echo OFF
javac ADFGX.java
javac ADFGVX.java
javac AffineAlphabet.java
javac Atbash.java
javac AutoKeyVigenere.java
javac Beaufort.java
javac Bifid.java
javac Caesar.java
javac Diana.java
javac Digraph.java
javac DoublePlayfair.java
javac ElsieFour.java
javac Enigma.java
javac FourSquare.java
javac Gronsfeld.java
javac KeyedColumnar.java
javac Kryha.java
javac Monoalphabetic.java
javac Nihilist.java
javac NullCipher.java
javac Playfair.java
javac RegularKeyedColumnar.java
javac RunningKey.java
javac ROT13.java
javac Sigaba.java
javac Solitaire.java
javac Spirale.java
javac StraddlingCheckerboard.java
javac TrueVigenere.java
javac -encoding ISO-8859-1 Tunny.java
javac VerticalTwoSquare.java
javac Vigenere.java
java ADFGX
java ADFGVX
java AffineAlphabet
java Atbash
java AutoKeyVigenere
java Beaufort
java Bifid
java Caesar
java Diana
java DoublePlayfair
java ElsieFour
java Enigma
java FourSquare
java Gronsfeld
java KeyedColumnar
java Kryha
java Monoalphabetic
java Nihilist
java NullCipher
java Playfair
java RegularKeyedColumnar
java ROT13
java RunningKey
java Sigaba
java Solitaire
java Spirale
java StraddlingCheckerboard
java TrueVigenere
java Tunny
java VerticalTwoSquare
java Vigenere