echo OFF
javac ADFGX.java
javac ADFGVX.java
javac AffineAlphabet.java
javac Atbash.java
javac AutoKeyVigenere.java
javac Beaufort.java
javac Bifid.java
javac Caesar.java
javac Diana.java
javac Digraph.java
javac DoublePlayfair.java
javac ElsieFour.java
javac Enigma.java
javac FourSquare.java
javac Gronsfeld.java
javac KeyedColumnar.java
javac Kryha.java
javac Monoalphabetic.java
javac Nihilist.java
javac NullCipher.java
javac Playfair.java
javac RegularKeyedColumnar.java
javac RunningKey.java
javac ROT13.java
javac Sigaba_CSP889.java
javac Sigaba_CSP2900.java
javac Solitaire.java
javac Spirale.java
javac StraddlingCheckerboard.java
javac -encoding ISO-8859-1 Sturgeon.java
javac TrueVigenere.java
javac T52ab.java
javac T52c.java
javac T52ca.java
javac T52d.java
javac T52e.java
javac -encoding ISO-8859-1 Tunny.java
javac VerticalTwoSquare.java
javac Vigenere.java
java ADFGX
java ADFGVX
java AffineAlphabet
java Atbash
java AutoKeyVigenere
java Beaufort
java Bifid
java Caesar
java Diana
java DoublePlayfair
java ElsieFour
java Enigma
java FourSquare
java Gronsfeld
java KeyedColumnar
java Kryha
java Monoalphabetic
java Nihilist
java NullCipher
java Playfair
java RegularKeyedColumnar
java ROT13
java RunningKey
java Sigaba_CSP889
java Sigaba_CSP2900
java Solitaire
java Spirale
java StraddlingCheckerboard
java TrueVigenere
java T52ab
java T52c
java T52ca
java T52d
java T52e
java Tunny
java VerticalTwoSquare
java Vigenere