echo OFF
javac ADFGX.java
javac AffineAlphabet.java
javac Atbash.java
javac AutoKeyVigenere.java
javac Beaufort.java
javac Bifid.java
javac Caesar.java
javac Digraph.java
javac DoublePlayfair.java
javac Enigma.java
javac FourSquare.java
javac Gronsfeld.java
javac KeyedColumnar.java
javac Kryha.java
javac Monoalphabetic.java
javac Nihilist.java
javac NullCipher.java
javac Playfair.java
javac ROT13.java
javac RegularKeyedColumnar.java
javac Sigaba.java
javac Solitaire.java
javac StraddlingCheckerboard.java
javac TrueVigenere.java
javac -encoding ISO-8859-1 Tunny.java
javac VerticalTwoSquare.java
javac Vigenere.java
java ADFGX
java AffineAlphabet
java Atbash
java AutoKeyVigenere
java Beaufort
java Bifid
java Caesar
java DoublePlayfair
java Enigma
java FourSquare
java Gronsfeld
java KeyedColumnar
java Kryha
java Monoalphabetic
java Nihilist
java NullCipher
java Playfair
java ROT13
java RegularKeyedColumnar
java Sigaba
java Solitaire
java StraddlingCheckerboard
java TrueVigenere
java Tunny
java VerticalTwoSquare
java Vigenere